Feature/group
Nexters/Strolling-of-time-API pull request #3
Opened 2019-08-08 22:40 UTC by woohyeonjo

group 완료

2019-08-08 22:57 UTC, mcauto commented
**[필수] 작업 시 자신이 생성한 파일을 변경시키지 않기**

자신의 작업 외 파일을 수정하면 상당히 높은 확률로 Conflict가 발생해서 누군가는 고통받아 

다른 사람의 코드에 의존된다면 테스트 코드를 작성해서 구현해 둔 뒤에 합칠 때 pull 하거나 코드리뷰에서 사용하는 편이 좋아

2019-08-09 02:36 UTC, mcauto requested changes

2019-08-09 02:36 UTC, mcauto commented on src/main/java/com/nexters/wiw/api/service/GroupService.java
> +        return groupRepository.save(groupRequestDto.toEntity());
**[필수] 예외에 대한 처리**

Repository와 Dto라는 객체를 사용할 때 발생할 수 있는 예외에 대한 처리가 있어야 할 것 같아

Validation error(bad request)랑 Database Error (Internal server error)를 처리해주어야 할 것 같아

[ControllerAdvice](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/bind/annotation/ControllerAdvice.html) 혹은 [RestControllerAdvice](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/bind/annotation/RestControllerAdvice.html) annotation을 사용해서 예외처리를 하는 방법이 있네

예외처리 방법은 [exception-handling-for-rest-with-spring](https://www.baeldung.com/exception-handling-for-rest-with-spring) 글을 참고하면 될 것 같아!

2019-08-09 02:36 UTC, mcauto commented on src/main/java/com/nexters/wiw/api/web/GroupController.java
> +        return ResponseEntity.ok().body(groupService.list());
**[권장] 결과를 처리하는 방법은 특별한 경우가 아니라면 통일**

ResponseEntity.ok() 또는 ResponseEntity.status(HTTPStatus.OK)는 통일하는 것이 좋을 것 같아.

```java
// pseudo code
groups = groupService.list();
statusCode = (group.size() > 0) ? HttpStatus.OK : HttpStatus.NOT_FOUND;
body = ? // 적절하게 에러 메시지 또는 list 결과
return ResponseEntity.status(statusCode).body(body)
```

2019-08-09 02:36 UTC, mcauto commented on src/main/java/com/nexters/wiw/api/domain/Group.java
> +    @Size(min = 1, max = 255)
**[선택] 상수는 공통으로 관리**

상수는 공통으로 사용하는 경우가 생길 수 있으므로 따로두고 같이 쓰는 것도 좋을 것 같아

2019-08-09 02:36 UTC, mcauto commented on src/main/java/com/nexters/wiw/api/service/GroupService.java
> +        return getGroup(id).get().update(groupRequestDto.toEntity());
**[권장] 함수 호출 체이닝 금지**

chaining은 모든 함수의 예외처리를 한꺼번에 하게 되고, 테스트하기가 어려워서 나중에 버그 발생 시 상당히 시간적인 비용을 잡아먹게 되므로 지양하는 것이 좋아

group 가져오기, optional의 get(), Group의 update() 를 다 분리해서 처리하는 것을 권장

Optional을 썼다면 `orElseThrow(Supplier<? extends X> exceptionSupplier)` 를 사용하고 Exception Handling 하는 것을 권장

[Java 8 optional](https://www.daleseo.com/java8-optional-after/)

2019-08-09 07:18 UTC, woohyeonjo commented
> **[필수] 작업 시 자신이 생성한 파일을 변경시키지 않기**
> 
> 자신의 작업 외 파일을 수정하면 상당히 높은 확률로 Conflict가 발생해서 누군가는 고통받아
> 
> 다른 사람의 코드에 의존된다면 테스트 코드를 작성해서 구현해 둔 뒤에 합칠 때 pull 하거나 코드리뷰에서 사용하는 편이 좋아

2019-08-13 10:48 UTC, woohyeonjo commented
sorry

2019-08-13 11:55 UTC, closed without merging