feature/group 완료하여 develop으로 merge 요청
Nexters/Strolling-of-time-API pull request #7
Opened 2019-08-15 07:35 UTC by woohyeonjo

CRUD 테스트 하였고
검색으로는 id, name(포함)으로 구현하였습니다.

2019-08-15 08:43 UTC, mcauto requested changes

2019-08-15 08:43 UTC, mcauto commented on src/main/java/com/nexters/wiw/api/service/GroupService.java
> +        if(isExistGroup(groupRequestDto.getName())) throw new GroupDuplicatedException();
[org.springframework.dao.DataIntegrityViolationException](https://github.com/Nexters/Strolling-of-time-API/blob/4b6be020d61f08276597d2aa5aac17822d44b075/src/main/java/com/nexters/wiw/api/exception/RestExceptionAdvisor.java#L41)이 예외처리 되어있어서 DB exist 체크 없이 `Repository.save()`를 호출해도 될 것 같아 

참고: https://stackoverflow.com/questions/26441658/sql-unique-manual-check-vs-catch-exception

다만 controller에서 발생된 예외 만을 handling하기 때문에 Controller에서 Service를 사용하지 않을 경우에는 Exception handling을 해주어야 해

2019-08-15 08:43 UTC, mcauto commented on src/main/java/com/nexters/wiw/api/ui/GroupRequestDto.java
> +    private int memberLimit = 6;
멤버 제한과 같은 상수는 다른 비즈니스 로직에서도 사용될 수 있으므로 따로 상수 클래스로 분리한 후 가져와서 쓰는 것이 좋을 것 같아

2019-08-15 08:43 UTC, mcauto commented on src/main/java/com/nexters/wiw/api/web/GroupController.java
> +@RequestMapping("/api/v1/group")
RequestMapping에 prefix를 지정해주고 controller의 함수에서 url을 사용하면
`/api/v1/group/groups`와 같은 방식으로 url이 생성되므로 ReqestMapping에 prefix는 `/api/v1`로 달아야할 것 같아

2019-08-15 08:43 UTC, mcauto commented on src/main/java/com/nexters/wiw/api/web/GroupController.java
> +    @PutMapping("groups/{id}")
put은 없으면 insert 있으면 update의 성격을 가지고 있어서 update라면 put보다는 patch를 쓰는 것이 좋을 것 같아

참고: https://medium.com/backticks-tildes/restful-api-design-put-vs-patch-4a061aa3ed0b

2019-08-15 08:43 UTC, mcauto commented on src/main/java/com/nexters/wiw/api/web/GroupController.java
> +    public ResponseEntity<Group> create(@RequestBody GroupRequestDto groupRequestDto){
GroupRequestDto의 validation check를 추가해야 할 것 같아

참고: [스프링 - @Valid Annotation을 이용한 유효성 체크](https://appsnuri.tistory.com/115)

2019-08-15 08:43 UTC, mcauto commented on src/main/java/com/nexters/wiw/api/config/SecurityConfig.java
> +}
파일의 마지막 라인은 한 줄 추가 권장

2019-08-15 08:43 UTC, mcauto commented on src/main/java/com/nexters/wiw/api/web/GroupController.java
> +    public ResponseEntity<List<Group>> getGroup(@RequestParam(value = "id", required = false) Long id,
group Resource를 가져오는 Read API를 작성할 때

일반적으로 list를 불러오는 end point와 item을 불러오는 end point 두 개를 두는 편이야

```java
@GetMapping("group/{id}")
public ReponseEntity<Group> getGroup();

@GetMapping("groups")
public ResponseEntity<List<Group>> getGroups(@RequestParam(value="keyword")); // usecase에 따라서 filter용 parameter 추가
```

이렇게 하면 if로 분기되는 복잡성을 줄일 수 있어

2019-08-15 08:43 UTC, mcauto commented on src/main/java/com/nexters/wiw/api/service/GroupService.java
> +        if(!isExistGroup(id)) throw new GroupNotExistedException();
delete에서도 exists 체크 없이 `repository.delete()`를 호출하게 하고 `org.springframework.dao.EmptyResultDataAccessException`를 Advisor에 등록해서 예외처리하면 될 것 같아

2019-08-15 08:57 UTC, mcauto requested changes

2019-08-15 08:57 UTC, mcauto commented on src/main/java/com/nexters/wiw/api/exception/GroupNotMatchException.java
> +    public GroupNotMatchException() {
그룹을 찾지 못한 예외는 NotFoundException을 상속받아서 GroupNotFoundException으로 사용하는 것이 좋을 것 같아

2019-08-15 08:57 UTC, mcauto commented on src/main/java/com/nexters/wiw/api/web/GroupController.java
> +    public ResponseEntity<List<Group>> getGroup(@RequestParam(value = "id", required = false) Long id,
get 요청 시 가져올 때 없으면  200 OK가 아닌 404 NotFound  예외처리를 해줘야 할 것 같아

참고: https://medium.com/@laeshiny/get-%EC%9A%94%EC%B2%AD-%EC%8B%9C-%EB%8D%B0%EC%9D%B4%ED%84%B0%EA%B0%80-%EC%97%86%EC%9C%BC%EB%A9%B4-200-or-404-4ab7430084af

2019-08-15 18:56 UTC, woohyeonjo commented on src/main/java/com/nexters/wiw/api/service/GroupService.java
> +        if(isExistGroup(groupRequestDto.getName())) throw new GroupDuplicatedException();
isExist를 제거하고 수행하였으나 name이 unique하지 않아 DataIntegrityViolationException이 일어나지 않았습니다. 따라서 name field에 @Column(unique = true)를 줌으로써 해결하였습니다.

2019-08-15 18:59 UTC, woohyeonjo commented on src/main/java/com/nexters/wiw/api/ui/GroupRequestDto.java
> +    private int memberLimit = 6;
memberLimit와 active field는 아직 수정 가능 여부가 확정되지 않아 그대로 두었고, default 값과 같은 상수를 지정해 놓으려 하였으나 상수 class의 디렉토리가 고민되어 작성하지 않았습니다.

2019-08-15 19:04 UTC, woohyeonjo commented on src/main/java/com/nexters/wiw/api/web/GroupController.java
> +@RequestMapping("/api/v1/group")
수정하였습니다.

2019-08-15 19:05 UTC, woohyeonjo commented on src/main/java/com/nexters/wiw/api/web/GroupController.java
> +    @PutMapping("groups/{id}")
patch로 수정하였습니다.

2019-08-15 19:07 UTC, woohyeonjo commented on src/main/java/com/nexters/wiw/api/web/GroupController.java
> +    public ResponseEntity<Group> create(@RequestBody GroupRequestDto groupRequestDto){
Validation check를 위해서 DTO의 각 field에 제약조건을 주고 ValidationExceptionAdvisor를 생성하여 핸들링 하였습니다.

2019-08-15 19:07 UTC, woohyeonjo commented on src/main/java/com/nexters/wiw/api/config/SecurityConfig.java
> +}
수정하였습니다.

2019-08-15 19:08 UTC, woohyeonjo commented on src/main/java/com/nexters/wiw/api/web/GroupController.java
> +    public ResponseEntity<List<Group>> getGroup(@RequestParam(value = "id", required = false) Long id,
위 내용대로 수정하고 데이터가 없을시 404 NotFound 처리를 하였습니다.

2019-08-15 19:12 UTC, woohyeonjo commented on src/main/java/com/nexters/wiw/api/service/GroupService.java
> +        if(!isExistGroup(id)) throw new GroupNotExistedException();
isExist를 제거하고 EmptyResultDataAccessException를 이용하여 예외 처리하였습니다. http status는 Bad Request로 처리하고, enum ErrorType에 BAD_ACCESS를 추가하였습니다.

2019-08-15 19:14 UTC, woohyeonjo commented on src/main/java/com/nexters/wiw/api/exception/GroupNotMatchException.java
> +    public GroupNotMatchException() {
기존의 GroupNotMatch, GroupDuplicated, GroupNotExist 예외를 삭제하고 NotFoundException을 상속받은 GroupNotFoundException을 추가하였습니다. (나머지 예외는 RestExceptionAdvisor가 처리해주기 때문에 삭제하였습니다.)

2019-08-15 23:59 UTC, mcauto commented on src/main/java/com/nexters/wiw/api/service/GroupService.java
> +        if(!isExistGroup(id)) throw new GroupNotExistedException();
없는 데이터에 접근했기 때문에 400이 아닌 404를 반환해주는것이 좋을 것 같아

2019-08-16 00:52 UTC, mcauto approved these changes

2019-08-16 00:53 UTC, merged